base_images:
  base:
    cluster: https://api.ci.openshift.org
    name: "4.5"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    cluster: https://api.ci.openshift.org
    name: release
    namespace: openshift
    tag: golang-1.13
canonical_go_repository: github.com/kubernetes-csi/external-attacher
images:
- dockerfile_path: Dockerfile.openshift
  from: base
  inputs:
    root:
      as:
      - "0"
      paths: null
  to: csi-external-attacher
promotion:
  name: "4.5"
  namespace: ocp
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tag_specification:
  cluster: https://api.ci.openshift.org
  name: "4.5"
  namespace: ocp
tests:
- as: unit
  commands: make test
  container:
    from: src
- as: e2e-aws-csi
  commands: make test-e2e ARTIFACT_DIR=/tmp/artifacts
  openshift_installer_custom_test_image:
    cluster_profile: aws
    from: stable:aws-ebs-csi-driver-operator-test
zz_generated_metadata:
  branch: master
  org: openshift
  repo: csi-external-attacher
