base_images:
  ocp_4.19_base-rhel9:
    name: "4.20"
    namespace: ocp
    tag: base-rhel9
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.16
images:
- dockerfile_path: Dockerfile
  from: aws-efs-utils-ironic-base
  inputs:
    ocp_4.19_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.19:base-rhel9
  to: aws-efs-utils-base
promotion:
  to:
  - name: "4.20"
    namespace: ocp
raw_steps:
- pipeline_image_cache_step:
    commands: |
      # Use ironic repos to get python3 packages
      # Copied from https://github.com/openshift/release/blob/c6736dd43d3ffa65cf8765801ad75c21705fe54a/ci-operator/config/openshift/ironic-image/openshift-ironic-image-main.yaml#L24-L30
      curl http://base-4-20-rhel-9-server-ironic.ocp.svc > /etc/yum.repos.art/ci/base-4-20-rhel-9-server-ironic.repo
    from: ocp_4.20_base-rhel9
    to: aws-efs-utils-ironic-base
releases:
  initial:
    integration:
      name: "4.20"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.20"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
zz_generated_metadata:
  branch: master
  org: openshift
  repo: aws-efs-utils
